web:
  image: nginx:latest
  ports:
    - "8080:80"
  volumes:
    - ./code:/code
    - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
  links:
    - php
    - redis

php:
  build: ./php-fpm/
  volumes: 
    - ./code:/code
    - ./conf/www.conf:/usr/local/etc/php-fpm.d/www.conf
    - ./code/logs/:/var/log/
  ports: 
    - "3306:3306"
    - "33060:33060"
  links: 
    - redis

redis:
  image: redis
